"""
pore_API.py
Reproduce the PoreAnalyser web service (poreanalyser.bioch.ox.ac.uk) locally on macOS.

Outputs (all land in ./poreanalyser_results/):
  *_aligned_z.pdb, *_aligned_z.pdb_circle.pdb, *_aligned_z.vmd, hole.out,
  hole_pathway_profile.csv/.png, ellipsoid_pathway_profile.csv/.png

Setup:
  conda create -n poreanalyser python=3.10 -y && conda activate poreanalyser
  pip install PoreAnalyser
  # plus a working macOS HOLE build at ~/.local/hole2/exe/
"""

import os
# Allow fork after macOS frameworks initialise. Must be set before anything
# touches the objc runtime, so keep it as the very first executable line.
os.environ.setdefault("OBJC_DISABLE_INITIALIZE_FORK_SAFETY", "YES")

import shutil
import multiprocessing as mp
from pathlib import Path

import matplotlib
matplotlib.use("Agg")          # no Cocoa GUI window; safe under fork, still saves figures

import PoreAnalyser as pa



# Alphafold File
src_pdb = "/Users/annasadilova/code/BMEIS_Hackathon2026/StructPhenotypes/data/alphafold/SCN1A/AF-P35498-F1-model_v6.pdb"



# =========================================================
# macOS HOLE fixup
# PoreAnalyser ships a Linux (ELF) HOLE binary that won't run on macOS and
# gives no executable= hook, so point its bundled binaries at the local
# macOS (Mach-O) build. Idempotent: re-applies itself after a pip upgrade.
# =========================================================
def ensure_macos_hole():
    pkg = Path(pa.__file__).parent / "hole2"
    src = Path.home() / ".local" / "hole2" / "exe"
    for exe in ("hole", "sph_process", "sos_triangle"):
        target, mac = pkg / exe, src / exe
        if not mac.exists():
            continue
        if target.is_symlink() and target.resolve() == mac.resolve():
            continue                                   # already linked
        if target.is_symlink():
            target.unlink()
        elif target.exists():                          # back up real Linux binary once
            backup = pkg / f"{exe}.linux.bak"
            if backup.exists():
                target.unlink()
            else:
                shutil.move(str(target), str(backup))
        os.symlink(mac, target)


# =========================================================
# PyMOL helper: written into the output folder so the pore can be
# viewed with `pymol -r pymol_pore_visu.py -- -structure ... -surface ...`
# =========================================================
PYMOL_VISU = '''\
"""pymol_pore_visu.py (auto-generated by pore_API.py)
Usage:
    pymol -r pymol_pore_visu.py -- -structure <aligned.pdb> -surface <cloud.pdb>
"""
from pymol import cmd
from pymol import __script__
from os import path
import sys
sys.path.append(path.dirname(__script__))
import argparse
 
parser = argparse.ArgumentParser()
parser.add_argument("-structure", nargs="?", const="__STRUCT__", default="__STRUCT__")
parser.add_argument("-surface",   nargs="?", const="__SURF__",   default="__SURF__")
args = parser.parse_args()
 
cmd.load(args.structure, "structure")
cmd.hide("all")
cmd.show("cartoon", "structure")
 
cmd.load(args.surface, "pore")
cmd.show("surface", "pore")
 
# cosmetic defaults so the pore is visible inside the protein
cmd.bg_color("white")
cmd.set("cartoon_transparency", 0.6, "structure")
cmd.color("grey70", "structure")
cmd.color("marine", "pore")
cmd.orient()
'''
 
 
def write_pymol_helper(aligned):
    """Write pymol_pore_visu.py + HOW_TO_VIEW.txt into cwd; return the two commands."""
    surf_circle = aligned + "_circle.pdb"           # spherical (HOLE) pore
    surf_ellip = aligned + "_ellipsoid.pdb"         # asymmetry-aware pore
    Path("pymol_pore_visu.py").write_text(
        PYMOL_VISU.replace("__STRUCT__", aligned).replace("__SURF__", surf_ellip)
    )
    cmd_circle = f"pymol -r pymol_pore_visu.py -- -structure {aligned} -surface {surf_circle}"
    cmd_ellip = f"pymol -r pymol_pore_visu.py -- -structure {aligned} -surface {surf_ellip}"
    Path("HOW_TO_VIEW.txt").write_text(
        "View the pore in PyMOL:\n\n"
        f"  spherical (HOLE) pore:\n    {cmd_circle}\n\n"
        f"  ellipsoidal pore:\n    {cmd_ellip}\n"
    )
    return cmd_circle, cmd_ellip




def main():
    ensure_macos_hole(src_pdb)

    # -----------------------------------------------------
    # Input + working dir
    # PoreAnalyser composes paths as `path_save + entry_in_pdb_array`, so pass a
    # BASENAME (not an absolute path) and run from the folder holding the PDB.
    # -----------------------------------------------------

    workdir = Path("poreanalyser_results").resolve()
    workdir.mkdir(exist_ok=True)

    basename = Path(src_pdb).name                      # AF-P35498-F1-model_v6.pdb
    shutil.copy(src_pdb, workdir / basename)
    os.chdir(workdir)                                  # all reads/writes now relative to here

    # -----------------------------------------------------
    # Initialise (path_save left as default '')
    # -----------------------------------------------------
    c = pa.PoreAnalysis(
        [basename],
        num_circle=24,
        end_radius=15,
        pathway_sel="protein",
        align_bool=True,
        # D_cation=1.33e-9,   # uncomment for sodium instead of the default potassium
    )

    # -----------------------------------------------------
    # 1) HOLE (spherical probe) -> csv, png, hole.out, .vmd
    # -----------------------------------------------------
    c.hole_analysis(plot_lines=True, legend_outside=False, title="", f_size=15)
    c.hole_df.to_csv("hole_pathway_profile.csv", index=False)
    c.hole_fig.savefig("hole_pathway_profile.png", dpi=200, bbox_inches="tight")

    radius_cols = [col for col in c.hole_df.columns if "Radius" in col]
    print("HOLE minimum radius (A):", float(c.hole_df[radius_cols].min().min()))

    # -----------------------------------------------------
    # 2) Point-cloud surface -> *_aligned_z.pdb_circle.pdb
    # -----------------------------------------------------
    c.pathway_visualisation(index_model=0, f_end="_circle.pdb")

    # -----------------------------------------------------
    # 3) Ellipsoidal probe (~1 min, multiprocessing) -> asymmetry-aware profile
    # -----------------------------------------------------
    df_ellipsoid = c.ellipsoid_analysis(index_model=0)
    if df_ellipsoid is None:                     # some versions store in the dict, not the return
        df_ellipsoid = c.ellipsoid_dfs[list(c.ellipsoid_dfs)[0]]
    fig_e = c.plt_pathway_ellipsoid(index_model=0)
    fig_e.savefig("ellipsoid_pathway_profile.png", dpi=200, bbox_inches="tight")
    df_ellipsoid.to_csv("ellipsoid_pathway_profile.csv", index=False)
    c.pathway_visualisation(index_model=0, f_end="_ellipsoid.pdb")

    # -----------------------------------------------------
    # 4) Heuristic conductance (pS)
    # -----------------------------------------------------
    result = c.conductance_estimation(index_model=0)
    g_hole_bulk, g_pa_bulk, g_hole, g_pa = result[:4]
    if len(result) > 4 and hasattr(result[4], "savefig"):   # 5th item is the resistance-vs-z figure
        result[4].savefig("conductance_resistance.png", dpi=200, bbox_inches="tight")
    print(f"Conductance (bulk):  HOLE={g_hole_bulk:.1f} pS  PoreAnalyser={g_pa_bulk:.1f} pS")
    print(f"Conductance (model): HOLE={g_hole:.1f} pS  PoreAnalyser={g_pa:.1f} pS")

    print("\nAll outputs in:", workdir)

    # -----------------------------------------------------
    # 5) Write the PyMOL visualisation helper + print commands
    # -----------------------------------------------------
    aligned = Path(c.names_aligned[0]).name
    cmd_circle, cmd_ellip = write_pymol_helper(aligned)
 
    print("\nView the pore in PyMOL (from inside this folder):")
    print("  spherical (HOLE) pore:")
    print("   ", cmd_circle)
    print("  ellipsoidal pore:")
    print("   ", cmd_ellip)
    print("(also saved to HOW_TO_VIEW.txt)")
 
    print("\nAll outputs in:", workdir)


if __name__ == "__main__":
    # PoreAnalyser's ellipsoid step uses multiprocessing. macOS defaults to
    # 'spawn', which re-imports this module per worker and can't pickle the live
    # MDAnalysis Universe -> bootstrapping RuntimeError / EOFError. Force 'fork'
    # (as on Linux) so workers inherit memory instead.
    try:
        mp.set_start_method("fork", force=True)
    except RuntimeError:
        pass
    main()